/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Audi_1.java
 *
 * Created on May 16, 2019, 11:17:02 PM
 */

package newpackage;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Audi extends javax.swing.JFrame {

    /** Creates new form Audi_1 */
    public Audi() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Car_Kind = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Chiller", 3, 36));
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("         HERE ARE SOME CARS MANUFACTURED BY AUDI");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 40);

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 3, 24));
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("SELECT MODEL");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 110, 200, 30);

        Car_Kind.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Here", "Audi A3", "Audi_Q3", "Audi Q7", "Audi R8", "Audi A3 CABRIOLET ", " ", " ", " " }));
        Car_Kind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Car_KindActionPerformed(evt);
            }
        });
        jPanel1.add(Car_Kind);
        Car_Kind.setBounds(360, 110, 110, 30);

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 3, 24));
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("SELECT MODEL");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 60, 200, 30);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(330, 60, 230, 30);

        jTable1.setFont(new java.awt.Font("Algerian", 0, 18));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "MODEL NAME", "MILEAGE", "ENGINE", "TRANSMISSION", "PRICE_EX_SHOWROOM"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 150, 900, 50);

        jLabel5.setText("select car");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 6));
        jLabel5.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel5AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 200, 510, 330);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/icons8-color-48.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(560, 60, 60, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/Audi-logo-wallpaper-high-resolution.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 40, 900, 490);

        jMenu1.setText("File");

        jMenuItem1.setText("back");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 897, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
  
        String name=jTextField1.getText();
    }//GEN-LAST:event_jTextField1KeyTyped

    private void Car_KindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Car_KindActionPerformed

        String name = jTextField1.getText();
               String Model_Name=(String)Car_Kind.getSelectedItem();
            DefaultTableModel d= (DefaultTableModel)jTable1.getModel();

            String Modelname;
            String Mileage1;
            String transmission1;
            String  Engine1;
            String  Price_Ex_showroom1;


        try {
            Class.forName("java.sql.DriverManager");
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost/project","root","123");
            Statement s=c.createStatement();
            String query;
           query="  select * from Audi_cars where Model_Name ='"+Model_Name+"' ; ";
        ResultSet rs  =s.executeQuery(query);


             if(rs.next())
             {
              do
              {
              Modelname=rs.getString(1);
               Mileage1 = rs.getString(2);
              Engine1 =rs.getString(3);
              transmission1=rs.getString(4);
               Price_Ex_showroom1=rs.getString(5);

              Object a[]={Modelname,Mileage1,Engine1,transmission1,Price_Ex_showroom1};
                    d.addRow(a);

              }while(rs.next());

                    }
             else{

                 JOptionPane.showMessageDialog(null, "information  not available");
             }
        c.close();
        rs.close();
        s.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
if(Car_Kind.getSelectedItem()=="Select here")
         {
              jLabel5.setIcon(null);
          }
          else if(Car_Kind.getSelectedItem()=="Audi A3")
        {
            ImageIcon picture= new ImageIcon("src/newpackage/audi a3.JPG");
                   jLabel5.setIcon(picture);
        }
 else if(Car_Kind.getSelectedItem()=="Audi_Q3")
        {
            ImageIcon picture= new ImageIcon("src/newpackage/audi q3.JPG");
                   jLabel5.setIcon(picture);
        }

    else if(Car_Kind.getSelectedItem()=="Audi Q7")
        {
            ImageIcon picture= new ImageIcon("src/newpackage/audi-q7.JPG");
                   jLabel5.setIcon(picture);
        }

    else if(Car_Kind.getSelectedItem()=="Audi A3")
        {
            ImageIcon picture= new ImageIcon("src/newpackage/audi a3.JPG");
                   jLabel5.setIcon(picture);
        }

    else if(Car_Kind.getSelectedItem()=="Audi R8")
        {
            ImageIcon picture= new ImageIcon("src/newpackage/audi r8.JPG");
                   jLabel5.setIcon(picture);
        }

          else if(Car_Kind.getSelectedItem()=="Audi A3 CABRIOLET")
        {
            ImageIcon picture= new ImageIcon("src/newpackage/audi-A3-cabriolet.JPG");
                   jLabel5.setIcon(picture);
        }
    else{jLabel5.setText("image not available");
    }





}//GEN-LAST:event_Car_KindActionPerformed

    private void jLabel5AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel5AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5AncestorAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String name = jTextField1.getText();

 DefaultTableModel d= (DefaultTableModel)jTable1.getModel();

            String Modelname;
            String Mileage1;
            String transmission1;
            String  Engine1;
            String  Price_Ex_showroom1;


        try {
            Class.forName("java.sql.DriverManager");
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost/project","root","123");
            Statement s=c.createStatement();
            String query;
           query="  select * from Audi_cars where Model_Name like'%"+name+"%' ; ";
        ResultSet rs  =s.executeQuery(query);


             if(rs.next())
             {
              do
              {
              Modelname=rs.getString(1);
               Mileage1 = rs.getString(2);
              Engine1 =rs.getString(3);
              transmission1=rs.getString(4);
               Price_Ex_showroom1=rs.getString(5);

              Object a[]={Modelname,Mileage1,Engine1,transmission1,Price_Ex_showroom1};
                    d.addRow(a);

              }while(rs.next());

                    }
             else{

                 JOptionPane.showMessageDialog(null, "table is empty");
             }
        c.close();
        rs.close();
        s.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
            if(Car_Kind.getSelectedItem()=="Select car")
         {
              jLabel5.setIcon(null);
          }
          else if(Car_Kind.getSelectedItem()=="Audi A3")
        {
            ImageIcon picture= new ImageIcon("src/newpackage/audi a3.JPG");
                   jLabel5.setIcon(picture);
        }
 else if(Car_Kind.getSelectedItem()=="Audi_Q3")
        {
            ImageIcon picture= new ImageIcon("src/newpackage/audi q3.JPG");
                   jLabel5.setIcon(picture);
        }

    else if(Car_Kind.getSelectedItem()=="Audi Q7")
        {
            ImageIcon picture= new ImageIcon("src/newpackage/audi-q7.JPG");
                   jLabel5.setIcon(picture);
        }

    else if(Car_Kind.getSelectedItem()=="Audi A3")
        {
            ImageIcon picture= new ImageIcon("src/newpackage/audi a3.JPG");
                   jLabel5.setIcon(picture);
        }

    else if(Car_Kind.getSelectedItem()=="Audi R8")
        {
            ImageIcon picture= new ImageIcon("src/newpackage/audi r8.JPG");
                   jLabel5.setIcon(picture);
        }

          else if(Car_Kind.getSelectedItem()=="Audi A3 Cabriolet")
        {
            ImageIcon picture= new ImageIcon("src/newpackage/audi r8.JPG");
                   jLabel5.setIcon(picture);
        }
          else
          {jLabel5.setText("image not available");}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         Car_Page1 p1= new Car_Page1();
        p1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Audi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox Car_Kind;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
