/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Delete_cars.java
 *
 * Created on Jun 30, 2019, 3:35:27 PM
 */

package newpackage;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author user
 */
public class Delete_cars extends javax.swing.JFrame {

    /** Creates new form Delete_cars */
    public Delete_cars() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bell MT", 3, 48));
        jLabel1.setText("  # DELETE RECORD");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 630, 50);

        jLabel5.setFont(new java.awt.Font("Bell MT", 3, 24));
        jLabel5.setText("ENTER  MODEL-NAME");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 200, 300, 40);

        jLabel6.setFont(new java.awt.Font("Bell MT", 3, 24));
        jLabel6.setText("ENTER  COMPANY");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 120, 250, 40);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 36));
        jPanel1.add(jTextField1);
        jTextField1.setBounds(260, 120, 310, 40);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 36));
        jPanel1.add(jTextField2);
        jTextField2.setBounds(310, 200, 310, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 48));
        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(80, 310, 410, 90);

        jMenu1.setText("File");

        jMenuItem1.setText("back");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String   manu =jTextField1.getText();
        String Model_name =jTextField2.getText();
        try {
              Class.forName("java.sql.DriverManager");
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost/project","root","123");
            Statement s=c.createStatement();
            String query;
           query="Delete from "+manu+" where Model_name='"+Model_name+"' ";
        s.executeUpdate(query);
   JOptionPane.showMessageDialog(null," record successully deleted");

        }
          catch (Exception e) {

          JOptionPane.showMessageDialog(null, e.getMessage());

          }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        User u1= new User();
    u1.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete_cars().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
