/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Sign_in.java
 *
 * Created on Jul 2, 2019, 10:15:07 PM
 */

package newpackage;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author user
 */
public class Sign_in extends javax.swing.JFrame {

    /** Creates new form Sign_in */
    public Sign_in() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 18));
        jLabel4.setForeground(new java.awt.Color(255, 204, 153));
        jLabel4.setText("                       WELCOME TO  OUR  CUSTOMER   \" LOGIN PAGE  \"            ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 850, 26);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/images.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(430, 250, 410, 150);

        jLabel5.setFont(new java.awt.Font("Bernard MT Condensed", 2, 18));
        jLabel5.setForeground(new java.awt.Color(255, 153, 153));
        jLabel5.setText("ENTER YOUR  NAME");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 255), 5));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 50, 180, 40);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(210, 50, 220, 40);

        jLabel6.setFont(new java.awt.Font("Bernard MT Condensed", 2, 18));
        jLabel6.setForeground(new java.awt.Color(255, 153, 153));
        jLabel6.setText("ENTER YOUR   last  NAME");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 255), 5));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 100, 180, 40);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(210, 100, 220, 40);

        jLabel7.setFont(new java.awt.Font("Bernard MT Condensed", 2, 18));
        jLabel7.setForeground(new java.awt.Color(255, 153, 153));
        jLabel7.setText("ENTER YOUR  mobile no");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 255), 5));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 150, 180, 40);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(210, 150, 220, 40);

        jLabel8.setFont(new java.awt.Font("Bernard MT Condensed", 2, 18));
        jLabel8.setForeground(new java.awt.Color(255, 153, 153));
        jLabel8.setText("ENTER YOUR  DOB");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 255), 5));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 200, 180, 40);

        jTextField4.setText("             /       /         ");
        jPanel1.add(jTextField4);
        jTextField4.setBounds(210, 200, 110, 40);

        jLabel9.setFont(new java.awt.Font("Bernard MT Condensed", 2, 18));
        jLabel9.setForeground(new java.awt.Color(255, 153, 153));
        jLabel9.setText("ENTER YOUR  USER NAME");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 255), 5));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(450, 50, 190, 40);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(650, 50, 180, 40);

        jLabel10.setFont(new java.awt.Font("Bernard MT Condensed", 2, 18));
        jLabel10.setForeground(new java.awt.Color(255, 153, 153));
        jLabel10.setText("ENTER YOUR  PASSWORD");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 255), 5));
        jPanel1.add(jLabel10);
        jLabel10.setBounds(450, 100, 190, 40);

        jLabel11.setFont(new java.awt.Font("Bernard MT Condensed", 2, 18));
        jLabel11.setForeground(new java.awt.Color(255, 153, 153));
        jLabel11.setText("VERIFY YOUR  PASSWORD");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 255), 5));
        jPanel1.add(jLabel11);
        jLabel11.setBounds(450, 160, 190, 40);

        jButton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 24));
        jButton2.setText("LOGIN");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 1, 1), 3));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 340, 267, 35);

        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 24));
        jButton1.setText("SIGN IN");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 1, 1), 3));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 280, 267, 35);
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(650, 170, 120, 20);
        jPanel1.add(jPasswordField2);
        jPasswordField2.setBounds(650, 110, 120, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     
        Login_Page l1= new Login_Page();
        l1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String name=   jTextField1.getText();
       String last_name=  jTextField2.getText();
        String mobile= jTextField3.getText();
        String dob= jTextField4.getText();
        String user_name= jTextField5.getText();
        String pwd = new String(jPasswordField1.getPassword());
        String pwd_2 = new String(jPasswordField1.getPassword());

            try {
           Class.forName("java.sql.DriverManager");
          Connection c=DriverManager.getConnection("jdbc:mysql://localhost/project","root","123");
         Statement s=c.createStatement();
         String query;
         query=" INSERT INTO SIGN_IN VALUES( '"+name+"','" +last_name+ "','" +mobile+"','" +dob+ "','" +user_name+"','" +pwd+"') ;" ;
        s.executeUpdate(query);

     JOptionPane.showMessageDialog(null, "one record inserted");

               Car_Page1 cb1= new Car_Page1();
        cb1.setVisible(true);
        this.dispose();

            }
        catch (Exception e)
        {
        JOptionPane.showMessageDialog(null, e.getMessage());
        }

   



}//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sign_in().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

}
